using Microsoft.Extensions.DependencyInjection;
#if (desktopHost)
using Runic.Application.Views.Desktop;
#else
using Runic.Application.Views.CsWebUi;
#endif
#if (viewModels == "reactiveui")
using Runic.Application.Views.ReactiveUI;
#endif

namespace RunicWindowApp;

public static class WorkspaceServices
{
    // Program.cs opens the Window with these services; tests can build the same graph.
    public static IServiceCollection AddWorkspace(this IServiceCollection services)
    {
#if (viewModels == "reactiveui")
        services.AddRunicReactiveModelContext();
#endif
        services.AddScoped<WorkspaceViewModel>();
        services.AddScoped<WelcomeViewModel>();
        services.AddScoped<CounterViewModel>();
        // Generated by the build: the Window and View Bridges and the View locator.
        services.AddRunicViews();
#if (desktopHost)
        // Per-window file dialogs, clipboard and file launcher from the provider for the running backend. A
        // ViewModel can take IFileDialogs, ITextClipboard or IWindowPlatformServices in its constructor; they
        // bind to the native window when it opens and report OwnerUnavailable until then, as in tests.
#else
        // Registers IFileDialogs, ITextClipboard and IWindowPlatformServices so ViewModels resolve on CS-WebUI.
        // CS-WebUI has no native window owner, so they report OwnerUnavailable; use --host desktop for native
        // dialogs and the clipboard.
#endif
        services.AddRunicPlatformServices();
        return services;
    }
}
